# -*- coding: utf-8 -*-
"""SCT - TASK1  INDIA POPULATION DISTRIBUTION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JcI-RQRGJAs6UQ71WwTKJA23x7t4k2oh
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/API_SP.POP.TOTL_DS2_en_csv_v2_5871594.csv")

df.head()

df.info()

df.describe()

df.shape

df.isnull().sum()

df.dtypes

df = df.fillna(method = "ffill")
df.head()

df.isnull().sum()

df.duplicated().sum()

df.nunique()

df['Country Name'].unique()

df['Country Code'].unique()

df['Indicator Name'].unique()

df.drop(['Indicator Name','Indicator Code','Country Code'],axis = 1, inplace = True)

df.head()

sns.heatmap(df.isnull())

df.columns

df = pd.DataFrame(df)

cols = [col for col in df.columns if col != 'Country Name']
cols

for i in cols:
    fig = plt.figure(figsize=(5,5))
    plt.hist(df[i],color='#222222',bins=10)
    plt.xlabel(i)
    plt.ylabel('Frequency')
    plt.title(f'Histogram for {i}')
    plt.show()

country_by_1960 = df.sort_values(by='1960').head(20)
country_by_1960

country_by_1960 = pd.DataFrame(df)

country_by_1960_t = country_by_1960.set_index('Country Name').T

for country_name, data_values in country_by_1960_t.iterrows():
    fig = plt.figure(figsize=(30, 15))
    sns.barplot(x=data_values.index, y=data_values.values)
    plt.xlabel('Year')
    plt.ylabel('Data Value')
    plt.title(f"{country_name} - Data Values from 1960 to 2022")
    plt.xticks(rotation=90)
    plt.show()

import seaborn as sns
for i in cols:
    fig = plt.figure(figsize=(5,5))
    sns.distplot(df[i],color='#222222',bins=10)
    plt.xlabel(i)
    plt.ylabel('Frequency')
    plt.title(f'distplot for {i}')
    plt.show()

import seaborn as sns
for i in cols:
    fig = plt.figure(figsize=(5,5))
    sns.scatterplot(df[i],color='#222222') #,bins=10)
    plt.xlabel(i)
    plt.ylabel('Frequency')
    plt.title(f'scatterplot for {i}')
    plt.show()

for i in cols:
    fig = plt.figure(figsize=(5,5))
    sns.barplot(df[i],color='#222222') #,bins=10)
    plt.xlabel(i)
    plt.ylabel('Frequency')
    plt.title(f'barplot for {i}')
    plt.show()

